### PR TITLE
(cli) Allow disabling of public access block configuration during ddk bootstrap

### PR DESCRIPTION
**Pull request by malachi-constant**
### Enhancement
- (Allow disabling of public access block configuration during `ddk bootstrap`

### Relates
- #112 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jaidisido** [comment]
Agreed - I don't think we should support every little flag available in cdk bootstrap or other commands. Like for CDK, our underlying bootstrap template can be customised by the user if they require anything beyond what the vanilla template offers

**Comment by kukushking** [comment]
@malachi-constant can't we parametrize the bootstrap template?

**Comment by jaidisido** [comment]
We can and we do already with some parameters. I just don't think that one is worth it. It also opens the door to similar requests when there is already the option of using a custom template

**Comment by kukushking** [comment]
IMO it's fairly minimal to add an `!If` into the template. I do agree that we have to put the foot down somewhere though

**Pull request closed without merging**
