### PR TITLE
feat: syncing `GlueTransformStage` to `main`

### LINKED ISSUE #261: typescript: update glue transform stage

### PR DESCRIPTION
**Pull request by malachi-constant**
### Feature or Bugfix
- syncing `GlueTransformStage` to `main`

### Relates
- Closes #261 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by anmolsgandhi — COMMENTED** [review]
Missing conditional catch (line 193): https://github.com/awslabs/aws-ddk/blob/main/core/aws_ddk_core/stages/glue_transform.py

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: DDKIntegrationTestsD8472609-5SCHWjldmWcf
* Commit ID: fc23b415386f9ed47b9f0168d7f2a4d12aaec22f
* Result: SUCCEEDED
* [Build Logs](https://9hm1y4sor9.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7131aafc-0078-4f08-8c09-9a12036e5bca%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by anmolsgandhi — APPROVED** [review]
Looks good !!

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: DDKIntegrationTestsD8472609-5SCHWjldmWcf
* Commit ID: 5521c8e7be0a35943424b46a275a3ab414c7ff98
* Result: SUCCEEDED
* [Build Logs](https://9hm1y4sor9.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5b65ef35-2af9-4d32-aa1a-3847e53ec6b1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Pull request merged**
